server:
  port: 8080
  servlet:
    context-path: /auth
spring:
  datasource:
    url: jdbc:mysql://cs544.c6wwj6rsn8el.us-east-1.rds.amazonaws.com:3306/cs544
    username: admin
    password: admin1234
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: health
app:
  jwt:
    secret: abcdefghijklmnOPQRSTUVWXYZ
#logging:
#  level:
#    root: DEBUG
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api.html