server:
  port: 8081
  servlet:
    context-path: /sport
management:
  endpoints:
    web:
      exposure:
        include: health
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/gameDb
services:
  auth:
    host: 172.31.81.163
    port: 8080
    context-path: /auth/
#  streaming:
#    host: localhost
#    port: 8082
#    context-path: /stream/
#logging:
#  level:
#    root: DEBUG
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api.html
aws:
  lambda-function: LiveGame
  accessKeyId: AKIA5BPWCK57NEG64B7Z
  secretAccessKey: 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